config/routes.rb
Rails.application.routes.draw do
  resources :rockets
  resources :agencies
  resources :pads
  resources :missions
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pad.rb
class Pad < ApplicationRecord
  validates :name,uniqueness: true
  validates :map, presence: true
  has_and_belongs_to_many :agencies
  has_many :rockets,through: :rocket_pads, dependent: :destroy
end

app/controllers/pads_controller.rb
class PadsController < ApplicationController
  before_action :set_pad, only: [:show, :edit, :update, :destroy]

  # GET /pads
  # GET /pads.json
  def index
    @pads = Pad.all
  end

  # GET /pads/1
  # GET /pads/1.json
  def show
  end

  # GET /pads/new
  def new
    @pad = Pad.new
  end

  # GET /pads/1/edit
  def edit
  end

  # POST /pads
  # POST /pads.json
  def create
    @pad = Pad.new(pad_params)

    respond_to do |format|
      if @pad.save
        format.html { redirect_to @pad, notice: 'Pad was successfully created.' }
        format.json { render :show, status: :created, location: @pad }
      else
        format.html { render :new }
        format.json { render json: @pad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pads/1
  # PATCH/PUT /pads/1.json
  def update
    respond_to do |format|
      if @pad.update(pad_params)
        format.html { redirect_to @pad, notice: 'Pad was successfully updated.' }
        format.json { render :show, status: :ok, location: @pad }
      else
        format.html { render :edit }
        format.json { render json: @pad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pads/1
  # DELETE /pads/1.json
  def destroy
    @pad.destroy
    respond_to do |format|
      format.html { redirect_to pads_url, notice: 'Pad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pad
      @pad = Pad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pad_params
      params.fetch(:pad, {})
    end
end

app/helpers/pads_helper.rb
module PadsHelper
end

app/views/pads/_form.html.erb
<%= form_with(model: pad, local: true) do |form| %>
  <% if pad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pad.errors.count, "error") %> prohibited this pad from being saved:</h2>

      <ul>
      <% pad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pads/edit.html.erb
<h1>Editing Pad</h1>

<%= render 'form', pad: @pad %>

<%= link_to 'Show', @pad %> |
<%= link_to 'Back', pads_path %>

app/views/pads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pads</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pads.each do |pad| %>
      <tr>
        <td><%= link_to 'Show', pad %></td>
        <td><%= link_to 'Edit', edit_pad_path(pad) %></td>
        <td><%= link_to 'Destroy', pad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pad', new_pad_path %>

app/views/pads/new.html.erb
<h1>New Pad</h1>

<%= render 'form', pad: @pad %>

<%= link_to 'Back', pads_path %>

app/views/pads/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pad_path(@pad) %> |
<%= link_to 'Back', pads_path %>