config/routes.rb
Rails.application.routes.draw do
  resources :rockets
  resources :agencies
  resources :pads
  resources :missions
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rocket.rb
class Rocket < ApplicationRecord
  has_many :pads,through: :rocket_pads, dependent: :destroy
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController
  before_action :set_rocket, only: [:show, :edit, :update, :destroy]

  # GET /rockets
  # GET /rockets.json
  def index
    @rockets = Rocket.all
  end

  # GET /rockets/1
  # GET /rockets/1.json
  def show
  end

  # GET /rockets/new
  def new
    @rocket = Rocket.new
  end

  # GET /rockets/1/edit
  def edit
  end

  # POST /rockets
  # POST /rockets.json
  def create
    @rocket = Rocket.new(rocket_params)

    respond_to do |format|
      if @rocket.save
        format.html { redirect_to @rocket, notice: 'Rocket was successfully created.' }
        format.json { render :show, status: :created, location: @rocket }
      else
        format.html { render :new }
        format.json { render json: @rocket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rockets/1
  # PATCH/PUT /rockets/1.json
  def update
    respond_to do |format|
      if @rocket.update(rocket_params)
        format.html { redirect_to @rocket, notice: 'Rocket was successfully updated.' }
        format.json { render :show, status: :ok, location: @rocket }
      else
        format.html { render :edit }
        format.json { render json: @rocket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rockets/1
  # DELETE /rockets/1.json
  def destroy
    @rocket.destroy
    respond_to do |format|
      format.html { redirect_to rockets_url, notice: 'Rocket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rocket
      @rocket = Rocket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rocket_params
      params.fetch(:rocket, {})
    end
end

app/helpers/rockets_helper.rb
module RocketsHelper
end

app/views/rockets/_form.html.erb
<%= form_with(model: rocket, local: true) do |form| %>
  <% if rocket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rocket.errors.count, "error") %> prohibited this rocket from being saved:</h2>

      <ul>
      <% rocket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :rocket_name %>
  </div>

  <div class="field">
    <%= form.label :wiki %>
    <%= form.text_field :wiki, id: :rocket_wiki %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img, id: :rocket_img %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rockets/edit.html.erb
<h1>Editing Rocket</h1>

<%= render 'form', rocket: @rocket %>

<%= link_to 'Show', @rocket %> |
<%= link_to 'Back', rockets_path %>

app/views/rockets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rockets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Wiki</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rockets.each do |rocket| %>
      <tr>
        <td><%= rocket.name %></td>
        <td><%= rocket.wiki %></td>
        <td><%= rocket.img %></td>
        <td><%= link_to 'Show', rocket %></td>
        <td><%= link_to 'Edit', edit_rocket_path(rocket) %></td>
        <td><%= link_to 'Destroy', rocket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rocket', new_rocket_path %>

app/views/rockets/new.html.erb
<h1>New Rocket</h1>

<%= render 'form', rocket: @rocket %>

<%= link_to 'Back', rockets_path %>

app/views/rockets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rocket.name %>
</p>

<p>
  <strong>Wiki:</strong>
  <%= @rocket.wiki %>
</p>

<p>
  <strong>Img:</strong>
  <%= @rocket.img %>
</p>

<%= link_to 'Edit', edit_rocket_path(@rocket) %> |
<%= link_to 'Back', rockets_path %>